# Topic 4: Outliers

### This file contains the 3 exercises assosiated with this topic. Please find references to each exercise in the README.md file

![Image4](https://miro.medium.com/max/697/1*O3lOgPwuHP7Vfc1T6NDRrQ.png)

In [2]:
# Import the required libraries:

import numpy as np

from numpy import genfromtxt

# Plotting:
import matplotlib.pyplot as plt

# Statistics:
import pandas as pd

# Visualisations:
import seaborn as sns

# Pandas for data analysis
import pandas as pd

# Morley dataset:
# Morley dataset has been given variable 'data1'



# Iris dataset URL:
#irisurl="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Importing
#irisDF = pd.read_csv(url)

# Dataset URL. Please note that this CSV file is compressed due to its size
#url="http://data.insideairbnb.com/ireland/leinster/dublin/2022-09-11/data/listings.csv.gz"

# Importing the CSV file:
#listingsDF = pd.read_csv(url, compression="gzip")

In [7]:
# Read in the morley data.
data1 = np.genfromtxt('../morley.csv', skip_header=1, delimiter=',', deletechars='"')

# Removing the first column
data1 = data1[:,1:]

print (data1)

[[1.00e+00 1.00e+00 8.50e+02]
 [1.00e+00 2.00e+00 7.40e+02]
 [1.00e+00 3.00e+00 9.00e+02]
 [1.00e+00 4.00e+00 1.07e+03]
 [1.00e+00 5.00e+00 9.30e+02]
 [1.00e+00 6.00e+00 8.50e+02]
 [1.00e+00 7.00e+00 9.50e+02]
 [1.00e+00 8.00e+00 9.80e+02]
 [1.00e+00 9.00e+00 9.80e+02]
 [1.00e+00 1.00e+01 8.80e+02]
 [1.00e+00 1.10e+01 1.00e+03]
 [1.00e+00 1.20e+01 9.80e+02]
 [1.00e+00 1.30e+01 9.30e+02]
 [1.00e+00 1.40e+01 6.50e+02]
 [1.00e+00 1.50e+01 7.60e+02]
 [1.00e+00 1.60e+01 8.10e+02]
 [1.00e+00 1.70e+01 1.00e+03]
 [1.00e+00 1.80e+01 1.00e+03]
 [1.00e+00 1.90e+01 9.60e+02]
 [1.00e+00 2.00e+01 9.60e+02]
 [2.00e+00 1.00e+00 9.60e+02]
 [2.00e+00 2.00e+00 9.40e+02]
 [2.00e+00 3.00e+00 9.60e+02]
 [2.00e+00 4.00e+00 9.40e+02]
 [2.00e+00 5.00e+00 8.80e+02]
 [2.00e+00 6.00e+00 8.00e+02]
 [2.00e+00 7.00e+00 8.50e+02]
 [2.00e+00 8.00e+00 8.80e+02]
 [2.00e+00 9.00e+00 9.00e+02]
 [2.00e+00 1.00e+01 8.40e+02]
 [2.00e+00 1.10e+01 8.30e+02]
 [2.00e+00 1.20e+01 7.90e+02]
 [2.00e+00 1.30e+01 8.10e+02]
 [2.00e+00

In [3]:
#morley dataset

morleyurl = pd.read(https://pages.ucsd.edu/~sdesposato/morley.data)

#https://pages.ucsd.edu/~sdesposato/morley.data

SyntaxError: invalid syntax (Temp/ipykernel_19500/4082554224.py, line 3)

# Exercise 1

#### Create box plots on a single set of axes for all five experiments in the morley data set.

# Exercise 2

#### Create box plots for all of the numercial variables in Fisher's Iris Data Set.

# Exercise 3

#### Adapt the above code and plots so that the overall plot is inversely propertional and the individual groups are directly proportional.